[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solagent_vault = "C5pqn3tYpivcZiQUhSbXeozSxZQ35P9e7VQTWzvRxr7o"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsc && npx mocha dist/tests/**/*.js -t 1000000"

[hooks]
